### PR TITLE
Added encode

### PR DESCRIPTION
**Pull request by alexkahler**
Added .encode() to line 33 and 34 to fix TypeError

### CODE REVIEW

**Comment by Schamper** [comment]
Which python version did you get an error with?

**Comment by Glingling** [comment]
i have this problem i'm on Python3.5.0 the last update.
I have modify like this and that's work : 
line 33 power_payload = b'\x00' + chr(len(live_id)).encode() + live_id + b'\x00'
line 34 power_header = b'\xdd\x02\x00' + chr(len(power_payload)).encode() + b'\x00\x00'

**Comment by jheiselman** [comment]
This fixed my issue.

$ python3 -V
Python 3.4.2

**Comment by kreonjr** [comment]
This fixed my issue as well.

$ python3 -V
Python 3.6.0

**Pull request merged**
